version: "3.9"

services:
  postgres:
    image: postgres:13.3
    container_name: bdsnowflake-postgres-1
    environment:
      POSTGRES_DB: snowfleak
      POSTGRES_USER: german
      POSTGRES_PASSWORD: 2104
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "./исходные данные:/data"
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: