services:
  postgresql:
    image: postgres:17
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lr1
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - lr1-net

  liquibase-migrations:
    container_name: lr1-migrations
    image: liquibase/liquibase:4.29
    depends_on:
      - postgresql
    command:
      - --searchPath=/changesets
      - --changelog-file=changelog.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/lr1
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/changesets
    networks:
      - lr1-net

volumes:
  postgresql_data:

networks:
  lr1-net:
    driver: bridge